language: php
sudo: required
dist: trusty

php:
  - 7.1
  - 7.2
  - 7.3

addons:
  chrome: stable

service:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE homestead_test;'

install:
  - cp .env.testing .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - php artisan key:generate

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - php artisan dusk